project_name: piping-server-check
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # NOTE: Drop Windows support because of syscall
      # - windows
      - darwin
      # TODO: Uncomment out when the development stabilized.
      # - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      # TODO: Uncomment out when the development stabilized.
      # - 386
      # - ppc64le
      # - s390x
      # - mips64
      # - mips64le
    goarm:
      - 6
      - 7
    main: ./main/main.go
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - license: MIT
    maintainer: Ryo Ota <nwtgck@nwtgck.org>
    homepage: https://github.com/nwtgck/piping-server-check
    description: "Check CLI for Piping Server"
    formats:
      - rpm
      - deb
    file_name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
release:
  github:
  disable: false
  prerelease: auto
  name_template: "v{{.Version}}"
brews:
  - tap:
      owner: nwtgck
      name: homebrew-piping-server-check
    homepage: "https://github.com/nwtgck/piping-server-check"
    description: "Check CLI for Piping Server"
